document.writeln("<div class=\'join_in\'>");
document.writeln("                    <div class=\'rowFluid\'>");
document.writeln("                        <div class=\'span12\'>");
document.writeln("                            <div class=\'container\'>");
document.writeln("                                <div class=\'join_in_title \'>红谷商标事务所，累计服务<span>10万+</span>创业者</div>");
document.writeln("                                <div class=\'join_in_text \'>从业以来，已为多家国内企业、个人提供过商标代理服务，同时，在加强业务水平方面参加行业领导机关的组织培训，与省内外各兄弟单位保持紧密的联系和广泛的业务合作交流，增广博闻，努力为客户提供更优越的服务。</div>");
document.writeln("                                <a href=\'#\' class=\'all_button join_in_button \' target=\'_blank\'>咨询电话：0791-83869220</a>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("");
document.writeln("                <div class=\'partners\'>");
document.writeln("                    <div class=\'rowFluid\'>");
document.writeln("                        <div class=\'span12\'>");
document.writeln("                            <div class=\'container\'>");
document.writeln("                                <div class=\'all_title1 \'>");
document.writeln("                                    <h3 class=\'title\'>联系我们</h3>");
document.writeln("                                    <div class=\'logo_formal\'><a href=\'#\' title=\'南昌红谷商标事务所有限公司\'> <img src=\'picture/logo_formal.svg\' alt=\'南昌红谷商标事务所有限公司\' width=50%> </a></div> ");
document.writeln("                                </div>");
document.writeln("                                ");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'footer \'>");
document.writeln("                    <div class=\'rowFluid\'>");
document.writeln("                        <div class=\'span12\'>");
document.writeln("                            <div class=\'container\'>");
document.writeln("                                <div class=\'footer_content\'>");
document.writeln("                                    <!--<div class=\'lianxi\'>全国分支机构</div>-->");
document.writeln("                                    <div class=\'span4 col-xm-6 col-xs-12 text_align\'>");
document.writeln("                                        <div class=\'footer_list\'>");
document.writeln("                                            <div class=\'footer_cotact\'>");
document.writeln("                                                <div class=\'footer_cotact_title text_align\'>服务项目</div>");
document.writeln("                                                <ul>");
document.writeln("                                                    <li class=\'span6 list_span6\'><a href=\'sbzc.html\'>商标注册</a></li>");
document.writeln("                                                    <li class=\'span6 list_span6\'><a href=\'zlsq.html\'>专利信息咨询申请</a></li>");
document.writeln("                                                    <li class=\'span6 list_span6\'><a href=\'bqdj.html\'>版权登记</a></li>");
document.writeln("                                                    <li class=\'span6 list_span6\'><a href=\'gszc.html\'>公司注册</a></li>");
document.writeln("                                                    <li class=\'span6 list_span6\'><a href=\'txmdj.html\'>条形码登记</a></li>");
document.writeln("                                                    <li class=\'span6 list_span6\'><a href=\'about.html\'>关于我们</a></li>");
document.writeln("                                                </ul>");
document.writeln("                                            </div>");
document.writeln("                                        </div>");
document.writeln("                                    </div>");
document.writeln("                                    <div class=\'span4 col-xm-6 col-xs-12 text_align\'>");
document.writeln("                                        <div class=\'footer_list\'>");
document.writeln("                                            <div class=\'footer_cotact\'>");
document.writeln("                                                <div class=\'footer_cotact_title text_align\'>南昌红谷商标事务所有限公司</div>");
document.writeln("                                                <ul>");
document.writeln("                                                    <li><span");
document.writeln("                                                            class=\'footer_cotact_content\'>联系地址：江西省南昌市红谷滩新区凤凰洲凤凰花园三期 A15 栋 8 号店面</span>");
document.writeln("                                                    </li>");
document.writeln("                                                    <li><span");
document.writeln("                                                            class=\'footer_cotact_content\'>联系人：申英</span>");
document.writeln("                                                    </li>");
document.writeln("                                                    <li><span class=\'footer_cotact_content\'>电话：<a href=\'#\' class=\'call\'>13687009969  13970084477  0791-83869220</a></span>");
document.writeln("                                                    </li>");
document.writeln("                                                </ul>");
document.writeln("                                            </div>");
document.writeln("                                        </div>");
document.writeln("                                    </div>");
document.writeln("");
document.writeln("                                    <div class=\'span4 col-xm-6 col-xs-12 text_align\'>");
document.writeln("                                        <div class=\'footer_list\'>");
document.writeln("                                            <div class=\'footer_cotact\'>");
document.writeln("                                                <div class=\'footer_cotact_title\'></div>");
document.writeln("                                                <ul>");
document.writeln("                                                    <li class=\'footer_qrcode\'><span");
document.writeln("                                                            class=\'footer_cotact_content\'>微信二维码</span>");
document.writeln("                                                        <img class=\'footer_qrcode\' src=\'images/xzapp.png\' alt=\'\'/>");
document.writeln("                                                    </li>");
document.writeln("                                                </ul>");
document.writeln("                                            </div>");
document.writeln("                                        </div>");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("");
document.writeln("                            ");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");