document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=Edge,chrome=1\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0, user-scalable=no\'>");
document.writeln("    <meta name=\'format-detection\' content=\'telephone=yes\'>");
document.writeln("    <meta http-equiv=\'Cache-Control\' content=\'no-transform\'/>");
document.writeln("    <meta http-equiv=\'Cache-Control\' content=\'no-siteapp\'/>");
document.writeln("    <title>南昌红谷商标事务所有限公司-商标注册,专利申请,版权登记等知识产权代理</title>");
document.writeln("    <meta name=\'description\' content=\'南昌红谷商标事务所有限公司，商标注册、续展、转让、变更、许可、设计、顾问等事务；      ");
document.writeln("    商标异议、答辩、争议、驳回复审、评审等事务；");
document.writeln("    江西省著名商标的认定；驰名商标认定，品牌推广；            ");
document.writeln("    专利咨询申请，版权登记，电子软件版权登记等其他知识产权代理服务；");
document.writeln("    条形码登记，条形码变更；条形码年检；");
document.writeln("    香港公司注册、国内公司注册、企业管理咨询，企业登记代理、等其他代理服务。 如有需要，敬请联系！服务热线：13687009969\'/>");
document.writeln("    <meta name=\'keywords\' content=\'注册公司,公司注册,工商注册,商标注册,代办营业执照\'/>");
document.writeln("    <meta name=\'renderer\' content=\'webkit\'>");
document.writeln("    <!--ico-->");
document.writeln("    <link rel=\'shortcut icon\' href=\'favicon.ico\'>");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'css/base.css\'/>");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'css/animate.min.css\'/>");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'css/owl.carousel.css\'/>");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'css/style.css\'/>");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'css/responsive.css\'/>");
document.writeln("    <script src=\'js/jquery-1.11.0.min.js\'></script>");
document.writeln("    <script src=\'js/wow.min_1.js\'></script>");
document.writeln("    <script src=\'js/owl.carousel.min.js\'></script>");
document.writeln("    <script src=\'js/page.js\'></script>");
document.writeln("    <style type=\'text/css\'>");
document.writeln("        <!--");
document.writeln("        .STYLE1 {");
document.writeln("            color: #FF0000");
document.writeln("        }");
document.writeln("");
document.writeln("        -->");
document.writeln("    </style>");
document.writeln("    <script language=\'javascript\' type=\'text/javascript\'>");
document.writeln("        var tags_a_array = document.getElementsByTagName(\'a\');");
document.writeln("        for (a in tags_a_array) {");
document.writeln("            a.onclick = function() {");
document.writeln("                console.log(\'a did touch\');");
document.writeln("            };");
document.writeln("        }");
document.writeln("    </script>");
document.writeln("    <!--<base target=\'_blank\'>-->");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\'header\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'rowFluid\'>");
document.writeln("            <div class=\'span3 col-md-12\'>");
document.writeln("                <div class=\'logo\'><a href=\'#\' title=\'南昌红谷商标事务所有限公司\'> <img src=\'picture/logo.svg\' alt=\'\'/> </a></div>");
document.writeln("            </div>");
document.writeln("            <div class=\'span9\'>");
document.writeln("                <div class=\'mobileMenuBtn\'><span class=\'span1\'></span><span class=\'span2\'></span><span");
document.writeln("                        class=\'span3\'></span></div>");
document.writeln("                <div class=\'mobileMenuBtn_shad\'></div>");
document.writeln("                <div class=\'header_menu\'>");
document.writeln("                    <ul id=\'menu\'>");
document.writeln("                        <li><a href=\'index.html\'>首页</a></li>");
document.writeln("                        <li><a href=\'sbzc.html\'>商标注册</a></li>");
document.writeln("                        <li><a href=\'zlsq.html\'>专利信息咨申请</a></li>");
document.writeln("                        <li><a href=\'gsbg.html\'>版权登记</a></li>");
document.writeln("                        <li><a href=\'gszx.html\'>公司注册</a></li>");
document.writeln("                        <li><a href=\'cjwt_news.html\'>常见问题</a></li>");
document.writeln("                        <li><a href=\'about.html\'>关于我们</a></li>");
document.writeln("                        <li><a href=\'contact_us.html\'>联系我们</a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'span2\'></div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("<div id=\'tool\'>");
document.writeln("    <ul class=\'toollist\'>");
document.writeln("        <li><a href=\'index.html\'><img src=\'picture/home.png\'>");
document.writeln("");
document.writeln("            <p>首页</p>");
document.writeln("        </a></li>");
document.writeln("        <li><a href=\'#\'><img src=\'picture/member.png\'>");
document.writeln("");
document.writeln("            <p>在线咨询</p>");
document.writeln("        </a></li>");
document.writeln("        <li class=\'li4\'><a href=\'tel:0791-83869220\'><img src=\'picture/tel.png\'/>");
document.writeln("");
document.writeln("            <p>一键拨打</p>");
document.writeln("        </a></li>");
document.writeln("        <li><a href=\'contact_us.html\'><img src=\'picture/map.png\'>");
document.writeln("");
document.writeln("            <p>服务网点</p>");
document.writeln("        </a></li>");
document.writeln("    </ul>");
document.writeln("</div>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");